# © 2022 Vlad-Stefan Harbuz <vlad@vladh.net>
# SPDX-License-Identifier: GPL-3.0-only

MusicRoot = "/mnt/music"

[[Stations]]
Id = "classical-post-1945"
Name = "Classical Post 1945"
Paths = [
    "Arnold Schoenberg",
    "Arvo Part",
    "Balanescu Quartet",
    "Ben Frost",
    "Brian Eno",
    "Colin Stetson & Sarah Neufeld",
    "David Lang",
    "Elaine Funaro",
    "Ellen Reid",
    "Floating Points",
    "Hans Zimmer",
    "Hilary Hahn",
    "Jessica Curry",
    "Jonny Greenwood",
    "Kammen and Swan",
    "Kjartan Sveinsson",
    "Kronos Quartet",
    "Leonard Bernstein",
    "Max Richter",
    "Michael Torke",
    "Pat Martino",
    "Philip Glass",
    "Rachel Grimes",
    "Rachel's",
    "Richard Reed Parry",
    "Ryuichi Sakamoto",
    "Steve Reich",
    "Taylor Deupree",
    "Trent Reznor & Atticus Ross",
    "William Basinski",
    "h hunt",
    "Óskar Guðjónsson & Skúli Sverrisson",
]

[[Stations]]
Id = "classical-pre-1945"
Name = "Classical Pre 1945"
Paths = [
    "Antonin Dvorak",
    "Bela Bartok",
    "Claude Debussy",
    "Edvard Grieg",
    "Edward Elgar",
    "Erik Satie",
    "Franz Schubert",
    "Frederic Chopin",
    "George Gershwin",
    "Gustav Mahler",
    "Johann Sebastian Bach",
    "Johannes Brahms",
    "John Dowland",
    "John Williams",
    "Ludwig van Beethoven",
    "Maurice Ravel",
    "Richard Strauss",
    "Sergei Rachmaninoff",
    "Shostakovich",
    "Tchaikovsky",
    "The Orthodox Singers",
    "Ukrainian Choir Dzvinochok",
    "Wolfgang Amadeus Mozart",
    "Yo-Yo Ma",
    "Yo-Yo Ma, Wynton Marsalis, Cho-Liang Lin",
]

[[Stations]]
Id = "hyperpop"
Name = "Hyperpop"
Paths = [
    "100 gecs",
    "Anamanaguchi",
    "Caroline Polachek",
    "Charli XCX",
    "Clarence Clarity",
    "Iglooghost",
    "Kai Whiston",
    "MEGAREX",
    "aldn",
    "gupi",
    "quinn",
]

[[Stations]]
Id = "japanese-and-korean"
Name = "Japanese and Korean"
Paths = [
    "Aimer",
    "BLACKPINK",
    "Back Number",
    "CAPSULE",
    "DADARAY",
    "Frederic",
    "GFRIEND",
    "GReeeeN",
    "Gesu no Kiwami Otome",
    "Haru Nemuri",
    "Haruka Nakamura",
    "Hyde",
    "Hyuna",
    "Ichiko Aoba",
    "Kitri",
    "Kyary Pamyu Pamyu",
    "L'Arc-en-Ciel",
    "Lamp",
    "MEGAREX",
    "MIYAVI",
    "MONDO GROSSO",
    "MONGOL800",
    "Masaki Suda",
    "Mito Tsukino",
    "Mono",
    "Official HIGE DANdism",
    "Perfume",
    "Polkadot Stingray",
    "RADWIMPS",
    "Rina Sawayama",
    "Ryuichi Sakamoto",
    "Shiina Ringo",
    "THREE1989",
    "Toe",
    "Tokyo Jihen",
    "Utada Hikaru",
    "Wednesday Campanella",
    "Yakushimaru Etsuko",
    "aimyon",
    "supercell",
]

[[Stations]]
Id = "pop"
Name = "Pop"
Paths = [
    "Allie X",
    "Ariana Grande",
    "Beyonce",
    "Carly Rae Jepsen",
    "Dua Lipa",
    "Rina Sawayama",
    "Taylor Swift",
    "The Format",
]

[[Stations]]
Id = "quiet-indie"
Name = "Quiet Indie"
Paths = [
    "Agnes Obel",
    "Aidan Knight",
    "Bon Iver",
    "Haruka Nakamura",
    "Ichiko Aoba",
    "Justin Vernon",
    "Kings of Convenience",
    "Right Away, Great Captain!",
    "Sufjan Stevens",
    "Yvette Young",
]

[[Stations]]
Id = "jazz"
Name = "Jazz"
Paths = [
    "Art Blakey & The Jazz Messengers",
    "Art Ensemble of Chicago",
    "Art Tatum",
    "Bill Evans",
    "Cannonball Adderley",
    "Charles Mingus",
    "Charlie Parker",
    "Dave Brubeck",
    "Django Reinhardt",
    "Eric Dolphy",
    "Hank Mobley",
    "Joe Pass",
    "John Coltrane",
    "John Zorn",
    "Kyle Eastwood",
    "Masada",
    "Miles Davis",
    "Milt Jackson & Modern Jazz Quartet",
    "Ornette Coleman",
    "The Dave Brubeck Quartet",
    "Thelonious Monk",
    "Tom Waits",
    "Wayne Shorter",
]
