userresources=$HOME/.Xresources
usermodmap=$HOME/.config/x11/Xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

exec i3
