userresources=$HOME/.config/x11/xresources
usermodmap=$HOME/.config/x11/xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

exec i3
