#!/bin/sh -eux

aur_install() {
    cd /tmp && git clone "https://aur.archlinux.org/$1.git" && cd "$1" && makepkg -si
}

sudo pacman -S \
    base linux linux-firmware \
    networkmanager avahi nss-mdns openssh inetutils bind mtr wol \
    doas git curl wget rsync which ranger ack fd duf btop powertop pv moreutils \
    perl-authen-sasl perl-file-mimeinfo perl-io-socket-ssl \
    gcc gdb make vim neovim tmux time man \
    pipewire pipewire-pulse pamixer playerctl smbclient cifs-utils \
    bluez bluez-utils brightnessctl \
    kitty nomacs mpv vlc zathura zathura-pdf-mupdf zathura-djvu aerc yt-dlp transmission-cli \
    cups cups-pdf ntfs-3g lxqt-policykit simple-scan \
    noto-fonts noto-fonts-emoji ttf-linux-libertine ttf-dejavu \
    xorg-server xorg-xinit xorg-xbacklight xorg-xinput xclip \
    i3-wm picom rofi feh maim slop redshift \
    sway swaybg wofi slurp swappy wl-clipboard

sudo systemctl enable --now NetworkManager
sudo systemctl enable --now avahi-daemon
sudo systemctl enable --now sshd

aur_install brother-dcp1610w
aur_install brscan4
aur_install greetd
aur_install greetd-tuigreet
aur_install mpdas
aur_install bluetuith
