#!/bin/sh -eux

aur_install() {
    if pacman -Qi "$1"; then
        printf "%s already installed\n" "$1"
        return
    fi
    mkdir -p /tmp/packages
    cd /tmp/packages
    git clone "https://aur.archlinux.org/$1.git"
    cd "$1"
    makepkg -si --needed
}

sudo pacman -S --needed \
    base linux linux-firmware \
    networkmanager avahi nss-mdns openssh inetutils bind mtr wol \
    doas git curl wget rsync which ranger ack fd duf btop powertop pv moreutils sshfs \
    perl-authen-sasl perl-file-mimeinfo perl-io-socket-ssl \
    gcc gdb make vim neovim tmux time man \
    mpd mpc ncmpcpp \
    pipewire pipewire-pulse pamixer playerctl smbclient cifs-utils \
    bluez bluez-utils brightnessctl \
    foot nomacs mpv vlc zathura zathura-pdf-mupdf zathura-djvu aerc yt-dlp transmission-cli speedcrunch \
    firefox telegram-desktop element-desktop signal-desktop \
    cups cups-pdf ntfs-3g lxqt-policykit simple-scan \
    ttf-ubuntu-font-family noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-dejavu ttf-linux-libertine ttf-ibm-plex ttf-liberation wqy-zenhei \
    fcitx5 fcitx5-mozc fcitx5-qt fcitx5-gtk fcitx5-configtool \
    sway swaybg wofi slurp swappy wl-clipboard waybar

aur_install brother-dcp1610w
aur_install brscan4
aur_install greetd
aur_install greetd-tuigreet
aur_install mpdas
aur_install bluetuith-bin
aur_install rate-mirrors
aur_install ttf-iosevka-term-ss07

if [ "$(hostname)" == "ki" ]; then
    sudo pacman -S --needed \
        xf86-video-nouveau mesa lib32-mesa
    aur_install nouveau-fw
fi

if [ "$(hostname)" == "something-that-needs-x" ]; then
    sudo pacman -S --needed \
        xorg-server xorg-xinit xorg-xbacklight xorg-xinput xclip \
        i3-wm picom rofi feh maim slop redshift
fi
