#!/bin/sh -eux

yay -S --needed \
    base linux linux-firmware \
    networkmanager avahi nss-mdns dnsmasq openssh inetutils bind mtr wol \
    doas git curl wget rsync which trash-cli ack fd fzf duf ncdu btop powertop pv moreutils sshfs \
    perl-authen-sasl perl-file-mimeinfo perl-io-socket-ssl \
    gcc gdb make vim neovim tmux time man \
    mpd mpc ncmpcpp \
    pipewire pipewire-pulse pamixer playerctl smbclient cifs-utils \
    bluez bluez-utils brightnessctl \
    foot nemo imv nomacs mpv vlc zathura zathura-pdf-mupdf zathura-djvu aerc yt-dlp transmission-cli speedcrunch \
    firefox telegram-desktop element-desktop signal-desktop \
    cups cups-pdf ntfs-3g lxqt-policykit simple-scan \
    ttf-ubuntu-font-family noto-fonts noto-fonts-cjk noto-fonts-emoji ttf-dejavu ttf-linux-libertine ttf-ibm-plex ttf-liberation wqy-zenhei ttf-bitstream-vera \
    fcitx5 fcitx5-mozc fcitx5-qt fcitx5-gtk fcitx5-configtool \
    sway swaybg wofi slurp grim swappy wl-clipboard waybar gammastep \
    \
    bluetuith-bin brother-dcp1610w brscan4 greetd greetd-tuigreet mpdas ranger-git \
    rate-mirrors ttf-iosevka-term-ss07 xcursor-chicago95-git

if [ "$(hostname)" == "ki" ]; then
    yay -S --needed \
        xf86-video-nouveau mesa lib32-mesa \
        \
        nouveau-fw
fi

if [ "$(hostname)" == "something-that-needs-x" ]; then
    yay -S --needed \
        xorg-server xorg-xinit xorg-xbacklight xorg-xinput xclip \
        i3-wm picom rofi feh maim slop redshift
fi
