#!/bin/sh -eu

if [ "$#" -ne 1 ]; then
  echo "Usage: art-convert <size>" >&2
  echo "\te.g. art-convert 2560" >&2
  exit 1
fi

fd -e jpg | while read fname; do
    dir=$(dirname "$fname")
    base=$(basename "$fname")
    outdir="../${1}x/$dir"
    mkdir -p "$outdir"
    echo "$fname"
    env MAGICK_TMPDIR=/tmp nice -5 \
        convert -limit memory 32 -limit map 32 "$fname" -resize "${1}x>" "$outdir/$base"
done
