#!/bin/sh -eu

if [ "$#" -ne 1 ]; then
  echo "Usage: art-convert <size>" >&2
  echo "\te.g. art-convert 2560x1440" >&2
  exit 1
fi

fd -e jpg | while read fname; do
    dir=$(dirname "$fname")
    base=$(basename "$fname")
    outdir="../${1}/$dir"
    mkdir -p "$outdir"
    echo "$fname"
    env MAGICK_TMPDIR="/mnt/balcora/cache" nice -2 \
        convert -limit memory 1GB -limit map 1GB "$fname" -resize "${1}>" "$outdir/$base"
done
