#!/bin/sh

set -e

if [ "$#" -ne 1 ]; then
  echo "1 argument required, $# provided"
  exit 1
fi

filename="$1"
filename_base="${filename%.*}"
filename_ext="${filename##*.}"
kindle_dedrm --kindle=B024160430620ESN "${filename}"
ebook-convert "${filename_base}.nodrm.${filename_ext}" "${filename_base}.epub"
rm "${filename_base}.nodrm.${filename_ext}"
