#!/bin/sh -eu

# This script copies text piped to it to the clipboard in a more-or-less
# cross-platform way.

case "$(uname -s)" in
    Darwin)
        exec pbcopy
        ;;

    Linux)
        which_exit_code=0
        which wl-copy > /dev/null 2>/dev/null || which_exit_code=$?
        if [ ${which_exit_code} -eq 0 ]; then
            exec wl-copy
        else
            exec xclip -sel c
        fi
        ;;

    CYGWIN*|MINGW32*|MSYS*|MINGW*)
        exec clip.exe
        ;;

    *)
        printf 'Unsupported OS\n'
        exit 1
        ;;
esac
