#!/bin/sh -eu

# This script copies text piped to it to the clipboard in a more-or-less
# cross-platform way.

case "$(uname -s)" in
    Darwin)
        exec pbcopy
        ;;

    Linux)
        if command -v "wl-copy" &> /dev/null; then
            exec wl-copy
        else
            exec xclip -sel c
        fi
        ;;

    CYGWIN*|MINGW32*|MSYS*|MINGW*)
        exec clip.exe
        ;;

    *)
        printf 'Unsupported OS\n'
        exit 1
        ;;
esac
