#!/bin/sh -eu

weekday_to_jp() {
    exec sed 's/Monday/月/g; s/Tuesday/火/g; s/Wednesday/水/g; s/Thursday/木/g; s/Friday/金/g; s/Saturday/土/g; s/Sunday/日/g'
}

# printf "%s\n" "$(date '+%A  %m/%d %H:%M' | weekday_to_jp)"
# printf "%s\n" "$(date '+%Y-%m-%d %H:%M')"
printf "%s\n" "$(date '+%a %b %d, %H:%M')"
