#!/bin/sh -eu


get_method() {
    method=$(dbus-send --session --dest=org.fcitx.Fcitx5 --print-reply \
        /controller org.fcitx.Fcitx.Controller1.CurrentInputMethod | \
        grep -Po '(?<=")[^"]+')

    if [ "$method" == "keyboard-us" ]; then
        echo "Ａ"
    elif [ "$method" == "mozc" ]; then
        echo "あ"
    fi
}


react() {
    while true; do
        read method
        if [ "$method" == "keyboard-us" ]; then
            echo "Ａ"
        elif [ "$method" == "mozc" ]; then
            echo "あ"
        fi
    done
}


get_method
dbus-monitor --session destination=org.freedesktop.IBus | \
    grep --line-buffered 'Fcitx5.*SetCurrentIM' -A 1 | \
    grep --line-buffered -oP 'string "\K.*(?=")' |
    react
