#!/bin/sh -u

print_sizes() {
    cd /mnt/balcora
    cat /home/vladh/bentus/dotfiles-extra/.config/kei-files | xargs -d '\n' du -shc
}

echo "File sizes:"
print_sizes
echo ""
echo "Space available:"
dfd
echo ""
read -p "Press any key..."
exec rsync -Pvrthl --delete --info=progress2 --files-from=/home/vladh/bentus/dotfiles-extra/.config/kei-files --exclude-from=/home/vladh/bentus/dotfiles-extra/.config/kei-files-ignored /mnt/balcora/ ~/kei/
