#!/bin/sh

echo "Copyright (c) 2022 Vlad-Stefan Harbuz <vlad@vladh.net>

All rights are reserved. You are granted a personal, non-assignable,
non-transferable, non-commercial license to use the source code for your own
personal educational purposes. Any other use, including any redistribution in
whole or in part, requires explicit, written permission from the copyright
holder.

The software is provided \"as is\" without warranty of any kind, either
express or implied, including without limitation any implied warranties of
condition, uninterrupted use, merchantability, fitness for a particular purpose,
or non-infringement." > LICENSE
