#!/bin/sh

echo "Copyright (c) 2022 Vlad-Stefan Harbuz <vlad@vladh.net>

Permission to use, copy, modify, and distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

The software is provided \"as is\" and the author disclaims all warranties
with regard to this software." > LICENSE
