#!/bin/sh -eu

repos="
alice-demettrie-bot
aoc-2020
aoc-2021
cheats-suck-but-are-easy
clumsycomputer
dewdrop
dotfiles
fotografiska
gbchon
glad
hare-3d-graphics
hare-gl
hare-glm
hare-peony
hare-project-library
hare-vulkan
hare-vulkan-hello-world
irabot
lein-sassy
macrotone
min-grub-theme
nouns
particles
peony
peony-vulkan-scaffold
pgmjs
plymouth-simplewallpaper
pstr
shimei
shimei.vim
snake-in-asm
squishymcbotty
starfield
tetris-in-go
thursday
tmk_keyboard_oldschool
vegvisir
virtualserial
"

if [ $# -eq 1 ]; then
    repos=$1
fi

for repo in $repos; do
    mirror-git-repo "git@git.sr.ht:~vladh/${repo}" "git@github.com:vladh/${repo}.git"
done
