#!/bin/sh -eu

repos="
alice-demettrie-bot
aoc-2020
aoc-2021
cheats-suck-but-are-easy
clumsycomputer
dewdrop
dotfiles
fotografiska
fotografiska2
gbchon
glad
hare-3d-graphics
hare-freetype2
hare-gl
hare-glm
hare-hazel
hare-pipewire
hare-project-library
hare-spapod
hare-vulkan
hare-vulkan-hello-world
hare-wav
hello-hare-wl
irabot
lein-sassy
lovebytetcc
macrotone
met.vladh.net
microblog
min-grub-theme
nouns
particles
peertube-theme-clumsycomputer
peony
peony-vulkan-scaffold
pgmjs
plymouth-simplewallpaper
pstr
radio-api
radio.vladh.net
shimei
shimei.vim
snake-in-asm
squishymcbotty
starfield
tetris-in-go
thursday
tmk_keyboard_oldschool
touchfiles
vegvisir
virtualserial
"

if [ $# -eq 1 ]; then
    repos=$1
fi

for repo in $repos; do
    mirror-git-repo "git@git.sr.ht:~vladh/${repo}" "git@github.com:vladh/${repo}.git"
done
