#!/bin/sh -eu

export BUPSTASH_KEY="/Users/niabon/Library/niabon-bupstash.key"
export BUPSTASH_REPOSITORY="/Volumes/backups/niabon/bupstash"
bupstash put \
    --send-log "/Volumes/backups/niabon/bupstash.sendlog" \
    /Users/niabon/Desktop
bupstash rm --allow-many older-than 30d 
