#!/bin/sh -eu

if [ $# -eq 0 ]; then
    echo "Usage: pa <filepath> [<remote-path>]"
    echo "\tThe remote path, if specified, must have a leading static/ or things/."
    exit
fi
if [ $# -eq 1 ]; then
    scp -r "$1" "vladh@yavin:/srv/www/vladh-website-static/things/"
fi
if [ $# -eq 2 ]; then
    scp -r "$1" "vladh@yavin:/srv/www/vladh-website-static/$2"
fi
