#!/bin/sh -eu

remote="yavin"
remote_root_dir="/srv/www/vladh-website-static/"
remote_url_prefix="https://vladh.net/"
dest_dir="t/"
global_dest_name=""
overwrite=0

if [ $# -eq 0 ]; then
    echo -e "pa: Uploads files to a server in an easy-to-use way."
    echo -e ""
    echo -e "Usage: pa [--static] [--as <newname>] <filepath>..."
    echo -e ""
    echo -e "If a file with a given name already exists on the server, a random"
    echo -e "suffix will be appended to the filename before the extension."
    echo -e ""
    echo -e "Flags:"
    echo -e "\t--static"
    echo -e "\t\tPuts the file in the static/ directory instead of the t/ directory."
    echo -e "\t--as <newname>"
    echo -e "\t\tTreats <newname> as the filename. Applies to all files,"
    echo -e "\t\twhich will be deduplicated as mentioned above."
    echo -e "\t-f"
    echo -e "\t\tOverwrites existing files with the same name."
    exit
fi

for arg in "$@"; do
    shift
    case $arg in
        --static)
            dest_dir="static/"
            ;;
        --as)
            global_dest_name="$1"
            shift
            ;;
        -f)
            overwrite=1
            ;;
        *)
            set -- "$@" "$arg"
            ;;
    esac
done

for arg in "$@"; do
    shift

    src_path="$arg"
    dest_name="${global_dest_name}"
    if [ -z "${dest_name}" ]; then
        dest_name=$(basename "${src_path}")
    fi
    dest_ext="${dest_name##*.}"
    dest_barename="${dest_name%.*}"

    if [ $overwrite -eq 0 ]; then
        test_exit_code=0
        ssh ${remote} "test -e \"${remote_root_dir}${dest_dir}${dest_name}\"" || test_exit_code=$?

        if [ $test_exit_code -eq 0 ]; then
            alnum=$(printf $RANDOM | md5sum | head -c 4)
            dest_barename="${dest_barename}-${alnum}"
            dest_name="${dest_barename}.${dest_ext}"
        fi
    fi

    scp -r "${src_path}" "${remote}:${remote_root_dir}${dest_dir}${dest_name}"

    echo "${remote_url_prefix}${dest_dir}${dest_name}"
done
