#!/bin/sh -eu

hostname=$(hostname)

if [ ! "$hostname" = "ki" ] && [ ! "$hostname" = "usu" ]; then
    while true; do
        read -p "Really poweroff ${hostname}? " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) exit;;
            * ) echo "Please answer y or n.";;
        esac
    done
fi

/usr/bin/poweroff "$@"
