#!/bin/sh -eu

if [ $# -eq 0 ]; then
    echo -e "Usage: proj [name]"
fi

case $1 in
    thanksd)
        cd ~/sources/thanksd.js
        swaymsg exec run-in-dir ~/sources/thanksd foot
        sleep 0.05
        swaymsg exec run-in-dir ~/sources/www-app foot
        sleep 0.05
        swaymsg exec run-in-dir ~/sources/thanksd.js foot
        sleep 0.05
        swaymsg exec run-in-dir ~/sources/thanksd foot
        sleep 0.05
        swaymsg exec run-in-dir ~/sources/www-app foot
        ;;
    *)
        ;;
esac
