#!/bin/sh

c_black='\e[30m'
c_red='\e[31m'
c_green='\e[32m'
c_yellow='\e[33m'
c_blue='\e[34m'
c_magenta='\e[35m'
c_cyan='\e[36m'
c_white='\e[97m'
c_reset='\e[39m'
c_bold='\e[1m'

if [ "$(uname)" = "Darwin" ] || [ "$(uname)" = "Linux" ] || [ "$(uname)" = "FreeBSD" ]; then
  prompt_char='$'
else
  prompt_char=">"
fi

git_prompt() {
  git_branch="$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')"
  if [ -n "$git_branch" ]; then
    echo ":${git_branch} "
  fi
}

venv_prompt() {
  if [ -n "${VIRTUAL_ENV}" ]; then
    echo "venv "
  fi
}

if [ -n "$BASH$FISH_VERSION" ]; then
  # Colours are enclosed in \[...\] so that they don't count towards the
  # character count and mess up scrolling etc.
  # PS1 used to be prefixed with: \[\033[G\]
  # What is that?
  export PS1="\[$c_blue\]\u \[$c_magenta\]\H\[$c_blue\] \W\$(git_prompt)\$(venv_prompt)$prompt_char \[$c_reset\]"
elif [ "$0" = "mrsh" ] || [ "$0" = "./imrsh" ] || [ "$0" = "." ] || [ $0 = "imrsh" ]; then
  export PS1='> '
else
  export PS1="$c_blue\u $c_magenta\H$c_blue \W\$(git_prompt)\$(venv_prompt)$prompt_char $c_reset"
fi
