#!/bin/sh

c_black='\e[30m'
c_red='\e[31m'
c_green='\e[32m'
c_yellow='\e[33m'
c_blue='\e[34m'
c_magenta='\e[35m'
c_cyan='\e[36m'
c_white='\e[97m'
c_reset='\e[39m'
c_bold='\e[1m'

uname_str="$(uname)"
prompt_char='◊'

host_prompt() {
  if pstree -p | grep --quiet ".*sshd.*\($$\)"; then
    echo "$(hostname) "
  fi
}

uname_prompt() {
  name="$(whoami)"
  if [ $name != "vladh" ]; then
    echo "$name "
  fi
}

git_prompt() {
  git_branch="$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')"
  if [ -n "$git_branch" ]; then
    echo ":${git_branch}"
  fi
}

venv_prompt() {
  if [ -n "${VIRTUAL_ENV}" ]; then
    echo "+venv"
  fi
}

case "$0" in
  *bash*)
    # Colours are enclosed in \[...\] so that they don't count towards the
    # character count and mess up scrolling etc.
    export PS1="\[$c_blue\]$(host_prompt)\[$c_magenta\]$(uname_prompt)\[$c_blue\]\W\$(git_prompt)\$(venv_prompt) $prompt_char \[$c_reset\]"
    ;;
  *mrsh*)
    export PS1='$ '
    ;;
  *)
    export PS1="$c_blue$(host_prompt)$c_magenta$(uname_prompt)$c_blue\W\$(git_prompt)\$(venv_prompt) $prompt_char $c_reset"
    ;;
esac
