#!/bin/sh -eu

if [ "$#" -lt 1 ]; then
  echo "Usage: yavin-acme [--issue|--renew]" >&2
  exit 1
fi

domain_params="$(yavin-getdomains | sed 's/^/-d /g' | xargs)"

export NSUPDATE_SERVER="localhost"
export NSUPDATE_KEY="/etc/bind/keys/all.key"

acme.sh --server letsencrypt --config-home /etc/acme/ --home /etc/acme/ --dns dns_nsupdate ${domain_params} $@

acme.sh --server letsencrypt --config-home /etc/acme/ --home /etc/acme --install-cert \
    -d 'vladh.net' \
    --key-file /etc/nginx/keys/key.pem \
    --fullchain-file /etc/nginx/keys/cert.pem \
    --reloadcmd 'systemctl reload nginx'
