#!/bin/sh -eu

options="-o '%(playlist_title)s/%(channel)s__%(title)s__%(id)s.%(ext)s' --cookies $HOME/bentus/dotfiles-extra/.config/yt-dlp/ytcookies.txt"

ids=$(yt-dlp $options --get-id --flat-playlist 'https://www.youtube.com/playlist?list=WL')

for f in ./Watch\ later/*; do
    [ -e "$f" ] || continue
    name="${f%.*}"
    id_candidate=$(printf "%s" $name | tail -c 11)
    found=0
    for id in $ids; do
        if [ "$id_candidate" == "$id" ]; then
            found=1
            break
        fi
    done
    if [ $found -eq 0 ]; then
        echo "Removing old file: $f"
        rm "$f"
    fi
done


exec yt-dlp $options 'https://www.youtube.com/playlist?list=WL'
