#!/bin/sh -eu

if [ $# -ne 1 ]; then
    echo -e "zotero-bib-clean: Cleans up .bib files exported by Zotero."
    echo -e ""
    echo -e "Usage: zotero-bib-clean <filepath>"
    exit 1
fi

sed \
    -e '/^\s\+keywords/d' \
    -e '/^\s\+file/d' \
    -e '/^@/ s/_\([0-9]\+\|nodate\),$/,/; /^@/ s/_/-/g' \
    -e '/^\s\+author = / { /, /! s/ = {/ = {{/; /, /! s/},$/}},/g }' \
    "$1"
