[api]
port=8102
host="127.0.0.1"

[queue]
random_song_api="http://localhost:8100/api/classical-post-1945/random"
song_fetch_url=""
np="http://localhost:8100/api/classical-post-1945/np"
nr=""
fallback="/mnt/balcora/bentus/archives-music/lobby.mp3"
buffer_duration=0
replaygain=false

[radio]
port=8202
host="127.0.0.1"
name="vladh radio: classical post 1945"
description=""
url="https://radio.vladh.net"
logo=""
private=false

[[streams]]
mount="stream192.mp3"
container="mp3"
bitrate=192
