[api]
port=8101
host="127.0.0.1"

[queue]
random_song_api="http://localhost:8100/api/japanese-and-korean/random"
song_fetch_url=""
np="http://localhost:8100/api/japanese-and-korean/np"
nr=""
fallback="/mnt/balcora/bentus/archives-music/lobby.mp3"
buffer_duration=0
replaygain=false

[radio]
port=8110
host="127.0.0.1"
name="vladh radio: japanese and korean"
description=""
url="https://radio.vladh.net"
logo=""
private=false

[[streams]]
mount="stream192.mp3"
container="mp3"
bitrate=192