[api]
port=8105
host="127.0.0.1"

[queue]
random_song_api="http://localhost:8100/api/pop/random"
song_fetch_url=""
np="http://localhost:8100/api/pop/np"
nr=""
fallback="/mnt/music/Dave Fleischer/lobby.mp3"
buffer_duration=0
replaygain=false

[radio]
port=8205
host="127.0.0.1"
name="vladh radio: pop"
description=""
url="https://radio.vladh.net"
logo=""
private=false

[[streams]]
mount="stream192.mp3"
container="mp3"
bitrate=192
